name: lumaka_sticker_quest
description: Lumaka - Sticker Quest App
publish_to: 'none' # da Schulprojekt, nicht auf pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8

  # Lokale Speicherung (für Todos)
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
